# Generated by Django 5.0.1 on 2024-02-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_dicription_alter_menu_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='dicription',
            new_name='menu_item_description',
        ),
    ]
