# Generated by Django 5.0.1 on 2024-07-24 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
